---
- name: Ensure TLS private key is available
  community.crypto.openssl_privatekey:
    path: "{{ prometheus_exporters_common_conf_dir }}/tls.key"
    size: "{{ prometheus_node_exporter_tls_selfsigned_key_size | default(omit) }}"
    type: "{{ prometheus_node_exporter_tls_selfsigned_key_type | default(omit) }}"
    curve: "{{ prometheus_node_exporter_tls_selfsigned_key_curve | default(omit) }}"
    regenerate: "{{ prometheus_node_exporter_tls_selfsigned_key_regenerate | default(omit) }}"
    owner: "{{ prometheus_exporters_common_user}}"
    group: "{{ prometheus_exporters_common_group }}"

- name: Ensure CSR is created from private key
  # We use the 'pipe' version because we don't want/need to write this to a file
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ prometheus_exporters_common_conf_dir }}/tls.key"
    common_name: "{{ prometheus_node_exporter_tls_selfsigned_csr_common_name | default(omit) }}"
  register: gencsr
  changed_when: false

- name: Ensure TLS certificate is available
  community.crypto.x509_certificate:
    path: "{{ prometheus_exporters_common_conf_dir }}/tls.crt"
    csr_content: "{{ gencsr.csr }}"
    owner: "{{ prometheus_exporters_common_user}}"
    group: "{{ prometheus_exporters_common_group }}"
    privatekey_path: "{{ prometheus_exporters_common_conf_dir }}/tls.key"
    # The ones below vary based on selfsigned or ownca
    provider: "{{ prometheus_node_exporter_tls_ownca | ternary('ownca', 'selfsigned') }}"
    ownca_content: "{{ prometheus_node_exporter_tls_ownca_content | default(omit) }}"
    ownca_privatekey_content: "{{ prometheus_node_exporter_tls_ownca_privatekey_content | default(omit) }}"

# - name: Ensure TLS certificate is available
#   community.crypto.x509_certificate:
#     path: "{{ prometheus_exporters_common_conf_dir }}/tls.crt"
#     csr_content: "{{ gencsr.csr }}"
#     owner: "{{ prometheus_exporters_common_user}}"
#     group: "{{ prometheus_exporters_common_group }}"
#     privatekey_path: "{{ prometheus_exporters_common_conf_dir }}/tls.key"
#     provider: selfsigned

# To ensure these are taken into account when constructing the web.yml file
- name: set key variables
  set_fact:
    # FIXME we can set dummy values - but what do we set?
    prometheus_node_exporter_tls_key: asdfas
    prometheus_node_exporter_tls_cert: asdfas
