---
- name: construct tls_server_config
  set_fact:
    tls_server_config: "{{ tls_server_config | default({}) | combine(
      {
        item:
          prometheus_exporters_common_conf_dir ~ '/' ~ tls_files | json_query('[?name==`' ~ item ~ '`].file|[0]')
      }
    ) }}"
  loop: "{{ prometheus_node_exporter_tls_server_config.keys() }}"
  loop_control:
    label: "{{ prometheus_exporters_common_conf_dir ~ '/' ~ tls_files | json_query('[?name==`' ~ item ~ '`].file|[0]') }}"


# With idempotent password hashing, also on older/buggy ansible versions
# See https://github.com/ansible/ansible/issues/36129
- name: construct basic_auth_users
  set_fact:
    basic_auth_users: "{{ basic_auth_users | default({}) | combine(
      {
        item.key: item.value |
          password_hash(
            'bcrypt',
            ('abcdef0ghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890' | shuffle(seed=inventory_hostname) | join)[:21] +
            ('Oeu' | shuffle(seed=inventory_hostname) | join)[1],
            rounds=9)
      }
    ) }}"
  loop: "{{ prometheus_node_exporter_basic_auth_users|dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  no_log: true

- name: ensure web.config file is available
  template:
    src: web.yml.j2
    dest: "{{ prometheus_exporters_common_conf_dir }}/web.yml"
    mode: 0640
    owner: "{{ prometheus_exporters_common_user}}"
    group: "{{ prometheus_exporters_common_group }}"

- name: ensure tls_server_config related files are available
  copy:
    dest: "{{ prometheus_exporters_common_conf_dir }}/{{ item.file }}"
    content: "{{ prometheus_node_exporter_tls_server_config[item.name] }}"
    mode: "{{ item.mode }}"
    owner: "{{ prometheus_exporters_common_user}}"
    group: "{{ prometheus_exporters_common_group }}"
  when:
    - item.name in prometheus_node_exporter_tls_server_config
  loop: "{{ tls_files }}"
  loop_control:
    label: "{{ prometheus_exporters_common_conf_dir }}/{{ item.file }}"
