---
- name: add 'web.config' to the config flags
  set_fact:
    prometheus_node_exporter_config_flags: "{{ prometheus_node_exporter_config_flags | combine(
      {
        'web.config': prometheus_exporters_common_conf_dir ~ '/web.yml'
      }
     ) }}"

- name: construct tls_server_config
  set_fact:
    tls_server_config: "{{ tls_server_config | default({}) | combine(
      {
        item.name ~ '_file':
          prometheus_exporters_common_conf_dir ~ '/' ~ item.file
      }
    ) }}"
  loop: "{{ tls_files }}"
  when: lookup('varnames', 'prometheus_node_exporter_tls_' ~ item.name)

# With idempotent password hashing, also on older/buggy ansible versions
# See https://github.com/ansible/ansible/issues/36129
- name: construct basic_auth_users
  set_fact:
    basic_auth_users: "{{ basic_auth_users | default({}) | combine(
      {
        item.key: item.value |
          password_hash(
            'bcrypt',
            ('abcdef0ghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890' | shuffle(seed=inventory_hostname) | join)[:21] +
            ('Oeu' | shuffle(seed=inventory_hostname) | join)[1],
            rounds=9)
      }
    ) }}"
  loop: "{{ prometheus_node_exporter_basic_auth_users|dict2items }}"
  when: prometheus_node_exporter_basic_auth_users is defined
  no_log: true

- name: ensure web.config file is available
  template:
    src: web.yml.j2
    dest: "{{ prometheus_exporters_common_conf_dir }}/web.yml"
    mode: 0640
    owner: "{{ prometheus_exporters_common_user}}"
    group: "{{ prometheus_exporters_common_group }}"

- name: ensure tls_server_config related files are available
  copy:
    dest: "{{ prometheus_exporters_common_conf_dir }}/{{ item.file }}"
    content: "{{ lookup('vars', 'prometheus_node_exporter_tls_' ~ item.name) }}"
    mode: "{{ item.mode }}"
    owner: "{{ prometheus_exporters_common_user}}"
    group: "{{ prometheus_exporters_common_group }}"
  loop: "{{ tls_files }}"
  loop_control:
    label: "{{ prometheus_exporters_common_conf_dir }}/{{ item.file }}"
  when: lookup('varnames', 'prometheus_node_exporter_tls_' ~ item.name)
